=== Darksider7/terkos/trunk/src/libCharacterDisplayMenu/resources/menu.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT menu (item+)>
<!ELEMENT item (item+|implementation-class)>
<!ATTLIST item
   text CDATA        #REQUIRED
>

<!ELEMENT implementation-class (property*)>
<!ATTLIST implementation-class
   name CDATA        #REQUIRED
>

<!ELEMENT property (#PCDATA)>
<!ATTLIST property
   key CDATA         #REQUIRED
   value CDATA       #IMPLIED
>

=== Darksider7/terkos/trunk/src/test/tinyxml++/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menu PUBLIC "-//CREATE Lab//TeRK//Menu//EN" "http://www.createlab.ri.cmu.edu/dtd/terk/menu/menu.dtd">

<menu>
   <item text="Audio">
      <item text="Set Volume">
         <item text="">
            <implementation-class name="edu.cmu.ri.createlab.demo.menu.action.SetVolumeMenuItemAction"/>
         </item>
      </item>
      <item text="Toggle Audio  Alerts">
         <item text="">
            <implementation-class name="edu.cmu.ri.createlab.demo.menu.action.ToggleAudioAlertsMenuItemAction">
               <property key="action.prompt">Enable Alerts?</property>
               <property key="choice.option1">Yes     </property>
               <property key="choice.option2">No</property>
               <property key="action.option1">Audio alerts    enabled.</property>
               <property key="action.option2">Audio alerts    disabled.</property>
            </implementation-class>
         </item>
      </item>
   </item>
   <item text="Factory Reset">
      <item text="Reset Motors">
         <item text="">
            <implementation-class name="edu.cmu.ri.createlab.demo.menu.action.ResetMotorsMenuItemAction">
               <property key="action.prompt">Reset Motors?</property>
               <property key="choice.option1">OK  </property>
               <property key="choice.option2">Cancel</property>
               <property key="action.option1">Motors reset to factory defaults</property>
               <property key="action.option2">Cancelled!</property>
            </implementation-class>
         </item>
      </item>
      <item text="Reset Network">
         <item text="">
            <implementation-class name="edu.cmu.ri.createlab.demo.menu.action.ResetNetworkMenuItemAction">
               <property key="action.prompt">Reset Network?</property>
               <property key="choice.option1">OK  </property>
               <property key="choice.option2">Cancel</property>
               <property key="action.option1">Network reset tofactory defaults</property>
               <property key="action.option2">Cancelled!</property>
            </implementation-class>
         </item>
      </item>
      <item text="Reset Servos">
         <item text="">
            <implementation-class name="edu.cmu.ri.createlab.demo.menu.action.ResetServosMenuItemAction">
               <property key="action.prompt">Reset Servos?</property>
               <property key="choice.option1">OK  </property>
               <property key="choice.option2">Cancel</property>
               <property key="action.option1">Servos reset to factory defaults</property>
               <property key="action.option2">Cancelled!</property>
            </implementation-class>
         </item>
      </item>
      <item text="Reset All">
         <item text="">
            <implementation-class name="edu.cmu.ri.createlab.demo.menu.action.ResetAllMenuItemAction">
               <property key="action.prompt">Reset All?</property>
               <property key="choice.option1">OK  </property>
               <property key="choice.option2">Cancel</property>
               <property key="action.option1">Reset to factorydefaults</property>
               <property key="action.option2">Cancelled!</property>
            </implementation-class>
         </item>
      </item>
   </item>
   <item text="System Info">
      <item text="Firmware             Version">
         <item text="">
            <implementation-class name="edu.cmu.ri.createlab.demo.menu.action.FirmwareVersionMenuItemAction"/>
         </item>
      </item>
      <item text="Hardware             Version">
         <item text="">
            <implementation-class name="edu.cmu.ri.createlab.demo.menu.action.HardwareVersionMenuItemAction"/>
         </item>
      </item>
   </item>
</menu>

=== Darksider7/terkos/trunk/src/lcdmenu/resources/lcd_menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menu PUBLIC "-//CREATE Lab//TeRK//Menu//EN" "http://www.createlab.ri.cmu.edu/dtd/terk/menu/menu.dtd">

<menu welcome-text="   Welcome to        TerkOS">
   <item text="System Info">
      <item text="Firmware             Version">
         <item text="">
            <implementation-class name="FirmwareVersionMenuItemAction" library="libSystemInfoMenuItemActions.so">
               <property key="label">Firmware version</property>
            </implementation-class>
         </item>
      </item>
      <item text="Hardware             Version">
         <item text="">
            <implementation-class name="HardwareVersionMenuItemAction" library="libSystemInfoMenuItemActions.so">
               <property key="label">Hardware version</property>
            </implementation-class>
         </item>
      </item>
   </item>
   <item text="Audio">
      <item text="Set Volume">
         <item text="">
            <implementation-class name="SetVolumeMenuItemAction" library="libAudioMenuItemActions.so"/>
         </item>
      </item>
      <item text="Toggle Audio  Alerts">
         <item text="">
            <implementation-class name="ToggleAudioAlertsMenuItemAction" library="libAudioMenuItemActions.so">
               <property key="action.prompt">Enable Alerts?</property>
               <property key="choice.option1">Yes     </property>
               <property key="choice.option2">No</property>
               <property key="action.option1">Audio alerts    enabled.</property>
               <property key="action.option2">Audio alerts    disabled.</property>
            </implementation-class>
         </item>
      </item>
      <item text="Reset Audio">
         <item text="">
            <implementation-class name="ResetAudioMenuItemAction" library="libResetMenuItemActions.so">
               <property key="action.prompt">Reset Audio?</property>
               <property key="choice.option1">OK  </property>
               <property key="choice.option2">Cancel</property>
               <property key="action.option1">Audio reset to  factory defaults</property>
               <property key="action.option2">Cancelled -- No settings changed</property>
            </implementation-class>
         </item>
      </item>
   </item>
   <item text="Wireless      Networking">
      <item text="Wireless      Status">
         <item text="">
            <implementation-class name="WirelessStatusMenuItemAction" library="libNetworkMenuItemActions.so">
               <property key="status.failure">Failed to get   wireless status.</property>
               <property key="status.unplugged">Wireless adapteris unplugged.</property>

               <property key="wireless-disabled.action.prompt">Wireless is off.</property>
               <property key="wireless-disabled.action.cancel"></property>
               <property key="wireless-disabled.choice.option1">Start   </property>
               <property key="wireless-disabled.choice.option2">OK</property>
               <property key="wireless-disabled.action.option1">You chose Start.</property>
               <property key="wireless-disabled.action.option2">Nothing to say here.</property><!--TODO-->
               
               <property key="wireless-enabled.action.prompt">Wireless is on.</property>
               <property key="wireless-enabled.action.cancel"></property>
               <property key="wireless-enabled.choice.option1">Info  </property>
               <property key="wireless-enabled.choice.option2">Stop</property>
               <property key="wireless-enabled.action.option2">Wireless is now turned off.</property>
               <property key="wireless-enabled.option1.failure">Could not obtainwireless details</property>
            </implementation-class>
         </item>
      </item>
      <item text="List Wireless Networks">
         <item text="">
            <implementation-class name="ViewWirelessNetworksMenuItemAction" library="libNetworkMenuItemActions.so"/>
         </item>
      </item>
      <item text="Start WirelessUpon Boot">
         <item text="">
            <implementation-class name="ToggleWirelessStartupUponBootMenuItemAction" library="libNetworkMenuItemActions.so">
               <property key="action.prompt">Start on boot?</property>
               <property key="choice.option1">Yes     </property>
               <property key="choice.option2">No</property>
               <property key="action.option1">Wireless will bestarted on boot.</property>
               <property key="action.option2">Wireless won't  start on boot.</property>
            </implementation-class>
         </item>
      </item>
      <item text="Reset WirelessSettings">
         <item text="">
            <implementation-class name="ResetWirelessNetworkingMenuItemAction" library="libResetMenuItemActions.so">
               <property key="action.prompt">Reset Wireless?</property>
               <property key="choice.option1">OK  </property>
               <property key="choice.option2">Cancel</property>
               <property key="action.option1">Wireless set to factory defaults</property>
               <property key="action.option2">Cancelled -- No settings changed</property>
            </implementation-class>
         </item>
      </item>
   </item>
   <item text="Factory Reset">
      <item text="Reset Audio">
         <item text="">
            <implementation-class name="ResetAudioMenuItemAction" library="libResetMenuItemActions.so">
               <property key="action.prompt">Reset Audio?</property>
               <property key="choice.option1">OK  </property>
               <property key="choice.option2">Cancel</property>
               <property key="action.option1">Audio reset to  factory defaults</property>
               <property key="action.option2">Cancelled -- No settings changed</property>
            </implementation-class>
         </item>
      </item>
      <item text="Reset Wireless">
         <item text="">
            <implementation-class name="ResetWirelessNetworkingMenuItemAction" library="libResetMenuItemActions.so">
               <property key="action.prompt">Reset Wireless?</property>
               <property key="choice.option1">OK  </property>
               <property key="choice.option2">Cancel</property>
               <property key="action.option1">Wireless set to factory defaults</property>
               <property key="action.option2">Cancelled -- No settings changed</property>
            </implementation-class>
         </item>
      </item>
      <item text="Reset User    Programs">
         <item text="">
            <implementation-class name="ResetUserProgramsMenuItemAction" library="libResetMenuItemActions.so">
               <property key="action.prompt">Reset Programs</property>
               <property key="choice.option1">OK  </property>
               <property key="choice.option2">Cancel</property>
               <property key="action.option1">Programs set to factory defaults</property>
               <property key="action.option2">Cancelled -- No settings changed</property>
            </implementation-class>
         </item>
      </item>
      <item text="Reset Web CtrlPanel Password">
         <item text="">
            <implementation-class name="ResetWebControlPanelPasswordMenuItemAction" library="libResetMenuItemActions.so">
               <property key="action.prompt">Reset Password</property>
               <property key="choice.option1">OK  </property>
               <property key="choice.option2">Cancel</property>
               <property key="action.option1">Password set to factory default</property>
               <property key="action.option2">Cancelled -- No settings changed</property>
            </implementation-class>
         </item>
      </item>
      <item text="Reset All">
         <item text="">
            <implementation-class name="ResetAllMenuItemAction" library="libResetMenuItemActions.so">
               <property key="action.prompt">Reset All?</property>
               <property key="choice.option1">OK  </property>
               <property key="choice.option2">Cancel</property>
               <property key="action.option1">Reset to factorydefaults</property>
               <property key="action.option2">Cancelled -- No settings changed</property>
            </implementation-class>
         </item>
      </item>
   </item>
</menu>

=== Darksider7/terkos/trunk/src/lcdmenu/resources/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menu PUBLIC "-//CREATE Lab//TeRK//Menu//EN" "http://www.createlab.ri.cmu.edu/dtd/terk/menu/menu.dtd">

<menu welcome-text="Welcome to Vex!    IFI, Inc.">
   <item text="Audio">
      <item text="Set Volume">
         <item text="">
            <implementation-class name="SetVolumeMenuItemAction" library="libAudioMenuItemActions.so"/>
         </item>
      </item>
      <item text="Toggle Audio  Alerts">
         <item text="">
            <implementation-class name="ToggleAudioAlertsMenuItemAction" library="libAudioMenuItemActions.so">
               <property key="action.prompt">Enable Alerts?</property>
               <property key="choice.option1">Yes     </property>
               <property key="choice.option2">No</property>
               <property key="action.option1">Audio alerts    enabled.</property>
               <property key="action.option2">Audio alerts    disabled.</property>
            </implementation-class>
         </item>
      </item>
      <item text="Reset Audio">
         <item text="">
            <implementation-class name="ResetAudioMenuItemAction" library="libAudioMenuItemActions.so">
               <property key="action.prompt">Reset Audio?</property>
               <property key="choice.option1">OK  </property>
               <property key="choice.option2">Cancel</property>
               <property key="action.option1">Audio reset to  factory defaults</property>
               <property key="action.option2">Cancelled!</property>
            </implementation-class>
         </item>
      </item>
   </item>
   <item text="Servos">
      <item text="View/Edit     Servo Configs">
         <item text="">
            <implementation-class name="ViewAndEditServoConfigsMenuItemAction" library="libServoMenuItemActions.so"/>
         </item>
      </item>
      <item text="Reset Servos">
         <item text="">
            <implementation-class name="ResetServosMenuItemAction" library="libServoMenuItemActions.so">
               <property key="action.prompt">Reset Servos?</property>
               <property key="choice.option1">OK  </property>
               <property key="choice.option2">Cancel</property>
               <property key="action.option1">Servos reset to factory defaults</property>
               <property key="action.option2">Cancelled!</property>
            </implementation-class>
         </item>
      </item>
   </item>
   <item text="Factory Reset">
      <item text="Reset Audio">
         <item text="">
            <implementation-class name="ResetAudioMenuItemAction" library="libAudioMenuItemActions.so">
               <property key="action.prompt">Reset Audio?</property>
               <property key="choice.option1">OK  </property>
               <property key="choice.option2">Cancel</property>
               <property key="action.option1">Audio reset to  factory defaults</property>
               <property key="action.option2">Cancelled!</property>
            </implementation-class>
         </item>
      </item>
      <item text="Reset Motors">
         <item text="">
            <implementation-class name="ResetMotorsMenuItemAction">
               <property key="action.prompt">Reset Motors?</property>
               <property key="choice.option1">OK  </property>
               <property key="choice.option2">Cancel</property>
               <property key="action.option1">Motors reset to factory defaults</property>
               <property key="action.option2">Cancelled!</property>
            </implementation-class>
         </item>
      </item>
      <item text="Reset Network">
         <item text="">
            <implementation-class name="ResetNetworkMenuItemAction">
               <property key="action.prompt">Reset Network?</property>
               <property key="choice.option1">OK  </property>
               <property key="choice.option2">Cancel</property>
               <property key="action.option1">Network reset tofactory defaults</property>
               <property key="action.option2">Cancelled!</property>
            </implementation-class>
         </item>
      </item>
      <item text="Reset Servos">
         <item text="">
            <implementation-class name="ResetServosMenuItemAction" library="libServoMenuItemActions.so">
               <property key="action.prompt">Reset Servos?</property>
               <property key="choice.option1">OK  </property>
               <property key="choice.option2">Cancel</property>
               <property key="action.option1">Servos reset to factory defaults</property>
               <property key="action.option2">Cancelled!</property>
            </implementation-class>
         </item>
      </item>
      <item text="Reset All">
         <item text="">
            <implementation-class name="ResetAllMenuItemAction">
               <property key="action.prompt">Reset All?</property>
               <property key="choice.option1">OK  </property>
               <property key="choice.option2">Cancel</property>
               <property key="action.option1">Reset to factorydefaults</property>
               <property key="action.option2">Cancelled!</property>
            </implementation-class>
         </item>
      </item>
   </item>
   <item text="System Info">
      <item text="Firmware             Version">
         <item text="">
            <implementation-class name="FirmwareVersionMenuItemAction" library="libSystemInfoMenuItemActions.so">
               <property key="label">Firmware version</property>
            </implementation-class>
         </item>
      </item>
      <item text="Hardware             Version">
         <item text="">
            <implementation-class name="HardwareVersionMenuItemAction" library="libSystemInfoMenuItemActions.so">
               <property key="label">Hardware version</property>
            </implementation-class>
         </item>
      </item>
   </item>
</menu>
